In [1]:
import numpy as np

A = np.array([[7, 2, 0],
              [-7, -2, 1],
              [1, 1, 0]])

B = np.array([[0, 2, 3],
              [1, 0, -2],
              [3, 1, 1]])


In [9]:
%%time
result_numpy = (np.dot(A, A) - np.dot(B, B)) * (A + B)
print(result_numpy)

[[168  28   9]
 [168  18   3]
 [-16 -14  -7]]
CPU times: total: 0 ns
Wall time: 0 ns


In [10]:
%%time
n = len(A)
m = len(A[0])

result_iterative = [[0]*m for _ in range(n)]

for i in range(n):
    for j in range(m):
        result_iterative[i][j] = (A[i][0]*A[0][j] + A[i][1]*A[1][j] + A[i][2]*A[2][j] -
                       B[i][0]*B[0][j] - B[i][1]*B[1][j] - B[i][2]*B[2][j]) * (A[i][j] + B[i][j])

for row in result_iterative:
    print(row)


[168, 28, 9]
[168, 18, 3]
[-16, -14, -7]
CPU times: total: 0 ns
Wall time: 998 µs


In [12]:
if np.allclose(result_numpy, result_iterative):
    print("Результати збігаються.")
else:
    print("Результати різняться.")

Результати збігаються.
