In [11]:
# Введення числа n
import numpy as np
import random
n = int(input("Введіть n: "))

Введіть n:  5


In [12]:
%%time
# Створення масиву одиниць розміром n×n за допомогою NumPy
array_np = np.zeros((n, n), dtype=int)

# Створення "рамки" з нулів
array_np[1:-1, 1:-1] = 1

print("Масив за допомогою NumPy:")
print(array_np)

Масив за допомогою NumPy:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
CPU times: total: 0 ns
Wall time: 1e+03 µs
